#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

Emporium\Svc\Alert\initApp();
$app = Emporium\Svc\Alert\app();

$kernel = $app->make('Illuminate\Contracts\Console\Kernel');

exit($kernel->handle(new ArgvInput, new ConsoleOutput));
